### ISSUE TITLE
"stop my server" results in hung docker instance if user clicks on "my server" before it is done

### ISSUE THREAD

**Issue by zogren** [jupyterhub/kubespawner#65]
We are testing this on gcloud:

If user goes to 
/hub/home
and clicks "stop my server" and waits they eventually see "my server" and when they click on that it does work
BUT
if the user clicks away and clicks on my server while server is stopping, they get into a state where kubectl says the image with the given username exists and thus a new one can not be started but JupyterHub seems to think none exist so "start my server" shows up on /hub/home and when user clicks on it  they get in an infinite redirect loop between
/hub/user/<userid>
and
/user/<userid>
The hub logs does not show any errors but does show the redirect loop of 302 responses

**Comment by yuvipanda** [comment]
Heya! Thank you for reporting it!

I think this should be mostly fixed in the #64 and JupyterHub 0.8. I'll verify and close after it is!

**Comment by zogren** [comment]
I see a related issue when stress testing where if spinning up a single user instance takes too long things get out of sync and it ends up in same state (instance exists but hub does not think it does so user cant log in)
Do you know if fix in #64 also helps fix this?

**Comment by zogren** [comment]
Switched to your branch an still get issue. It seems to happen if DB entry for node disappears or never gets created but docker instance with that name did get created. Fix could be to delete on create if it already exists or something like that?

**Comment by zogren** [comment]
Guess I should wait till you merge. When I try to use your branch I get 
"The 'spawner_class' trait of <jupyterhub.app.JupyterHub object at 0x7f5f61eab940> instance must be a type, but 'kubespawner.KubeSpawner' could not be imported"
but it looks like I also need to add something new to my helm chart?

**Comment by yuvipanda** [comment]
I think we fixed this in https://github.com/jupyterhub/jupyterhub/pull/1356.

**Comment by yuvipanda** [comment]
And it seems to work with master.

**Comment by minrk** [comment]
Closing as this may be fixed by #174 (or other fixes since then)
